const toolDomains = {
"ChatGPT":"openai.com","Google Gemini":"gemini.google.com","Microsoft Copilot":"copilot.microsoft.com",
"Claude":"anthropic.com","Perplexity AI":"perplexity.ai","Pi AI":"pi.ai",
"Character AI":"character.ai","YouChat":"you.com","Poe":"poe.com","Meta AI":"meta.ai",
"DeepSeek":"deepseek.com",
"Grammarly":"grammarly.com","Jasper AI":"jasper.ai","Copy.ai":"copy.ai",
"Writesonic":"writesonic.com","Rytr":"rytr.me","QuillBot":"quillbot.com",
"Wordtune":"wordtune.com","Sudowrite":"sudowrite.com","Notion AI":"notion.so","HyperWrite":"hyperwriteai.com",
"Midjourney":"midjourney.com","DALL·E":"openai.com","Stable Diffusion":"stability.ai",
"Leonardo AI":"leonardo.ai","Adobe Firefly":"firefly.adobe.com","Canva AI":"canva.com",
"Runway ML":"runwayml.com","Playground AI":"playgroundai.com","Clipdrop":"clipdrop.co","DreamStudio":"dreamstudio.ai",
"Pictory":"pictory.ai","Synthesia":"synthesia.io","HeyGen":"heygen.com",
"Lumen5":"lumen5.com","Descript":"descript.com","Runway":"runwayml.com",
"VEED IO":"veed.io","InVideo AI":"invideo.io","Kapwing":"kapwing.com","FlexClip":"flexclip.com",
"GitHub Copilot":"github.com","Codeium":"codeium.com","Replit Ghostwriter":"replit.com",
"Tabnine":"tabnine.com","Amazon CodeWhisperer":"aws.amazon.com","Cursor":"cursor.com",
"Phind":"phind.com","Blackbox AI":"blackbox.ai","Mutable AI":"mutable.ai","Sourcegraph Cody":"sourcegraph.com",
"ClickUp AI":"clickup.com","Zapier AI":"zapier.com","Motion":"usemotion.com",
"Fireflies AI":"fireflies.ai","Otter AI":"otter.ai","Taskade":"taskade.com",
"Mem AI":"mem.ai","Superhuman AI":"superhuman.com","Tome":"tome.app",
"Surfer SEO":"surferseo.com","Frase":"frase.io","Scalenut":"scalenut.com",
"GrowthBar":"growthbarseo.com","MarketMuse":"marketmuse.com","INK AI":"inkforall.com",
"Outranking":"outranking.io","Clearscope":"clearscope.io","AdCreative AI":"adcreative.ai","Ocoya":"ocoya.com",
"Khanmigo":"khanacademy.org","Socratic":"socratic.org","Quizlet AI":"quizlet.com",
"Gradescope":"gradescope.com","Duolingo Max":"duolingo.com","Elicit":"elicit.com",
"Scholarcy":"scholarcy.com","Explainpaper":"explainpaper.com","Perlego AI":"perlego.com","Wolfram Alpha AI":"wolframalpha.com",
"ElevenLabs":"elevenlabs.io","Murf AI":"murf.ai","PlayHT":"play.ht",
"Resemble AI":"resemble.ai","Speechify":"speechify.com","Soundraw":"soundraw.io",
"AIVA":"aiva.ai","Boomy":"boomy.com","Voicemod AI":"voicemod.net",
"AutoGPT":"agpt.co","AgentGPT":"agentgpt.reworkd.ai","BabyAGI":"babyagi.org",
"Hugging Face":"huggingface.co","Replicate":"replicate.com","LangChain":"langchain.com",
"Flowise":"flowiseai.com","Jan AI":"jan.ai","LM Studio":"lmstudio.ai","AnythingLLM":"anythingllm.com",
"Descript Audio":"descript.com"
};
