const tools = [
// Chatbots & Conversational AI
{name:"ChatGPT",rating:4.7,reviews:12840,views:"1.2M",desc:"AI chatbot by OpenAI for text generation, coding, content creation, and conversational assistance.",tags:["Chatbots & Conversational AI","Writing & Content Creation","Coding & Developer Tools"]},
{name:"Google Gemini",rating:4.5,reviews:6750,views:"680K",desc:"Multimodal AI assistant by Google that understands text, images, audio, and video across Google products.",tags:["Chatbots & Conversational AI","Coding & Developer Tools","Productivity & Automation"]},
{name:"Microsoft Copilot",rating:4.3,reviews:5400,views:"520K",desc:"AI assistant embedded across Microsoft 365 for writing, data analysis, and coding in VS Code.",tags:["Chatbots & Conversational AI","Productivity & Automation","Coding & Developer Tools"]},
{name:"Claude",rating:4.6,reviews:4800,views:"410K",desc:"Anthropic's AI assistant known for safety, long context windows, and nuanced reasoning.",tags:["Chatbots & Conversational AI","Writing & Content Creation","Education & Study Tools"]},
{name:"Perplexity AI",rating:4.5,reviews:3900,views:"350K",desc:"AI-powered search engine that provides cited, real-time answers to complex questions.",tags:["Chatbots & Conversational AI","Education & Study Tools"]},
{name:"Pi AI",rating:4.2,reviews:1800,views:"120K",desc:"Personal AI by Inflection, designed for friendly, supportive conversations and emotional intelligence.",tags:["Chatbots & Conversational AI"]},
{name:"Character AI",rating:4.1,reviews:8200,views:"900K",desc:"Create and chat with AI characters — fictional, historical, or custom personalities.",tags:["Chatbots & Conversational AI"]},
{name:"YouChat",rating:4.0,reviews:1200,views:"95K",desc:"AI chat integrated into You.com search engine with real-time web access and citations.",tags:["Chatbots & Conversational AI"]},
{name:"Poe",rating:4.2,reviews:2100,views:"180K",desc:"Quora's platform giving access to multiple AI models including GPT-4, Claude, and Gemini in one place.",tags:["Chatbots & Conversational AI"]},
{name:"Meta AI",rating:4.3,reviews:3200,views:"280K",desc:"Meta's AI assistant powered by Llama, integrated across WhatsApp, Instagram, and Facebook.",tags:["Chatbots & Conversational AI","Productivity & Automation"]},
{name:"DeepSeek",rating:4.4,reviews:3200,views:"320K",desc:"Open-source AI model offering advanced reasoning, coding, and math capabilities rivaling top proprietary models.",tags:["Chatbots & Conversational AI","Coding & Developer Tools","Education & Study Tools"]},

// Writing & Content Creation
{name:"Grammarly",rating:4.6,reviews:15200,views:"2.1M",desc:"AI writing assistant for grammar, clarity, tone, and style improvements across all platforms.",tags:["Writing & Content Creation","Productivity & Automation"]},
{name:"Jasper AI",rating:4.4,reviews:5600,views:"420K",desc:"AI content platform for marketing teams to create blog posts, ads, emails, and social media content.",tags:["Writing & Content Creation","Marketing & SEO"]},
{name:"Copy.ai",rating:4.3,reviews:4100,views:"310K",desc:"AI copywriting tool for generating marketing copy, product descriptions, and social media posts.",tags:["Writing & Content Creation","Marketing & SEO"]},
{name:"Writesonic",rating:4.2,reviews:3400,views:"250K",desc:"AI writer for SEO-optimized articles, landing pages, ads, and product descriptions.",tags:["Writing & Content Creation","Marketing & SEO"]},
{name:"Rytr",rating:4.1,reviews:2800,views:"190K",desc:"Affordable AI writing assistant supporting 30+ languages and 40+ content templates.",tags:["Writing & Content Creation"]},
{name:"QuillBot",rating:4.4,reviews:9800,views:"1.5M",desc:"AI paraphrasing and summarizing tool popular with students and professionals.",tags:["Writing & Content Creation","Education & Study Tools"]},
{name:"Wordtune",rating:4.3,reviews:3600,views:"280K",desc:"AI writing companion that rewrites sentences for clarity, tone, and fluency.",tags:["Writing & Content Creation"]},
{name:"Sudowrite",rating:4.2,reviews:1400,views:"85K",desc:"AI writing tool designed specifically for fiction authors and creative storytelling.",tags:["Writing & Content Creation"]},
{name:"Notion AI",rating:4.5,reviews:7200,views:"580K",desc:"AI built into Notion for writing, summarizing, brainstorming, and organizing notes.",tags:["Writing & Content Creation","Productivity & Automation"]},
{name:"HyperWrite",rating:4.1,reviews:1600,views:"110K",desc:"AI writing assistant that learns your style and helps draft emails, essays, and content.",tags:["Writing & Content Creation"]},

// Image Generation & Design
{name:"Midjourney",rating:4.7,reviews:18500,views:"2.5M",desc:"Leading AI image generator known for stunning, artistic visuals from text prompts.",tags:["Image Generation & Design"]},
{name:"DALL·E",rating:4.5,reviews:11200,views:"1.8M",desc:"OpenAI's image generation model creating realistic and creative images from text descriptions.",tags:["Image Generation & Design"]},
{name:"Stable Diffusion",rating:4.4,reviews:8900,views:"1.2M",desc:"Open-source AI image generator offering full control and local deployment options.",tags:["Image Generation & Design","Coding & Developer Tools"]},
{name:"Leonardo AI",rating:4.5,reviews:6200,views:"480K",desc:"AI image generation platform with fine-tuned models for game assets, concept art, and design.",tags:["Image Generation & Design"]},
{name:"Adobe Firefly",rating:4.4,reviews:5800,views:"620K",desc:"Adobe's generative AI for creating images, text effects, and design elements within Creative Cloud.",tags:["Image Generation & Design"]},
{name:"Canva AI",rating:4.6,reviews:8920,views:"890K",desc:"AI-powered design platform for creating visuals, presentations, and marketing materials with ease.",tags:["Image Generation & Design","Marketing & SEO","Productivity & Automation"]},
{name:"Runway ML",rating:4.4,reviews:4100,views:"340K",desc:"Creative AI toolkit for image generation, video editing, and visual effects.",tags:["Image Generation & Design","Video Creation & Editing"]},
{name:"Playground AI",rating:4.2,reviews:2400,views:"180K",desc:"Free AI image generator with mixed editing capabilities and community sharing.",tags:["Image Generation & Design"]},
{name:"Clipdrop",rating:4.3,reviews:3100,views:"250K",desc:"AI-powered visual tools for background removal, image upscaling, and object removal.",tags:["Image Generation & Design"]},
{name:"DreamStudio",rating:4.2,reviews:2000,views:"150K",desc:"Stability AI's official interface for Stable Diffusion image generation.",tags:["Image Generation & Design"]},

// Video Creation & Editing
{name:"Pictory",rating:4.3,reviews:3200,views:"240K",desc:"AI video creator that turns blog posts and scripts into short branded videos automatically.",tags:["Video Creation & Editing","Marketing & SEO"]},
{name:"Synthesia",rating:4.5,reviews:4800,views:"380K",desc:"AI video platform creating professional videos with realistic AI avatars in 130+ languages.",tags:["Video Creation & Editing"]},
{name:"HeyGen",rating:4.4,reviews:3600,views:"290K",desc:"AI video generator with customizable avatars for marketing, training, and social content.",tags:["Video Creation & Editing","Marketing & SEO"]},
{name:"Lumen5",rating:4.2,reviews:2800,views:"210K",desc:"AI-powered video maker that transforms text content into engaging video presentations.",tags:["Video Creation & Editing","Marketing & SEO"]},
{name:"Descript",rating:4.5,reviews:5200,views:"420K",desc:"All-in-one audio/video editor with AI transcription, screen recording, and text-based editing.",tags:["Video Creation & Editing","Audio, Voice & Music AI"]},
{name:"Runway",rating:4.4,reviews:3800,views:"310K",desc:"AI creative suite for video generation, editing, and visual effects with Gen-2 model.",tags:["Video Creation & Editing","Image Generation & Design"]},
{name:"VEED IO",rating:4.3,reviews:4100,views:"350K",desc:"Online video editor with AI subtitles, translations, and background removal.",tags:["Video Creation & Editing"]},
{name:"InVideo AI",rating:4.2,reviews:3400,views:"270K",desc:"AI video creator that generates publish-ready videos from simple text prompts.",tags:["Video Creation & Editing"]},
{name:"Kapwing",rating:4.1,reviews:2600,views:"220K",desc:"Online collaborative video editor with AI-powered tools for content creators.",tags:["Video Creation & Editing"]},
{name:"FlexClip",rating:4.0,reviews:1800,views:"140K",desc:"Easy-to-use AI video maker with templates for marketing, social media, and presentations.",tags:["Video Creation & Editing","Marketing & SEO"]},

// Coding & Developer Tools
{name:"GitHub Copilot",rating:4.6,reviews:14200,views:"1.8M",desc:"AI pair programmer by GitHub that suggests code completions and entire functions in your editor.",tags:["Coding & Developer Tools"]},
{name:"Codeium",rating:4.4,reviews:5600,views:"380K",desc:"Free AI code completion and chat assistant supporting 70+ programming languages.",tags:["Coding & Developer Tools"]},
{name:"Replit Ghostwriter",rating:4.3,reviews:3200,views:"250K",desc:"AI coding assistant built into Replit's online IDE for code generation and debugging.",tags:["Coding & Developer Tools"]},
{name:"Tabnine",rating:4.2,reviews:4800,views:"340K",desc:"AI code assistant that runs locally for privacy-first code completions and suggestions.",tags:["Coding & Developer Tools"]},
{name:"Amazon CodeWhisperer",rating:4.3,reviews:3800,views:"290K",desc:"Amazon's AI coding companion with security scanning and AWS integration.",tags:["Coding & Developer Tools"]},
{name:"Cursor",rating:4.5,reviews:6100,views:"450K",desc:"AI-first code editor built on VS Code with deep AI integration for writing and editing code.",tags:["Coding & Developer Tools"]},
{name:"Phind",rating:4.3,reviews:2400,views:"180K",desc:"AI search engine for developers that provides code solutions with explanations.",tags:["Coding & Developer Tools"]},
{name:"Blackbox AI",rating:4.1,reviews:2000,views:"150K",desc:"AI coding assistant for code generation, search, and extracting code from images.",tags:["Coding & Developer Tools"]},
{name:"Mutable AI",rating:4.0,reviews:1200,views:"85K",desc:"AI-powered tool for auto-generating tests, documentation, and refactoring code.",tags:["Coding & Developer Tools"]},
{name:"Sourcegraph Cody",rating:4.3,reviews:2800,views:"200K",desc:"AI coding assistant with full codebase context for accurate code generation and answers.",tags:["Coding & Developer Tools"]},

// Productivity & Automation
{name:"ClickUp AI",rating:4.3,reviews:4200,views:"320K",desc:"AI assistant within ClickUp for writing tasks, summaries, and project planning.",tags:["Productivity & Automation"]},
{name:"Zapier AI",rating:4.4,reviews:5100,views:"410K",desc:"AI-powered automation platform connecting 6,000+ apps with natural language workflows.",tags:["Productivity & Automation"]},
{name:"Motion",rating:4.3,reviews:2800,views:"190K",desc:"AI calendar and project manager that auto-schedules tasks and optimizes your day.",tags:["Productivity & Automation"]},
{name:"Fireflies AI",rating:4.4,reviews:3600,views:"280K",desc:"AI meeting assistant that records, transcribes, and summarizes meetings automatically.",tags:["Productivity & Automation","Audio, Voice & Music AI"]},
{name:"Otter AI",rating:4.3,reviews:4800,views:"380K",desc:"AI meeting transcription and note-taking tool with real-time collaboration features.",tags:["Productivity & Automation","Audio, Voice & Music AI"]},
{name:"Taskade",rating:4.1,reviews:1800,views:"120K",desc:"AI-powered workspace for task management, mind maps, and team collaboration.",tags:["Productivity & Automation"]},
{name:"Mem AI",rating:4.0,reviews:1400,views:"95K",desc:"AI-powered note-taking app that self-organizes and surfaces relevant information.",tags:["Productivity & Automation"]},
{name:"Superhuman AI",rating:4.4,reviews:2600,views:"180K",desc:"AI-powered email client for writing, summarizing, and managing email at blazing speed.",tags:["Productivity & Automation","Writing & Content Creation"]},
{name:"Tome",rating:4.2,reviews:3200,views:"240K",desc:"AI presentation tool that generates slides, narratives, and visuals from prompts.",tags:["Productivity & Automation","Writing & Content Creation"]},

// Marketing & SEO
{name:"Surfer SEO",rating:4.4,reviews:4200,views:"320K",desc:"AI-powered SEO tool for content optimization, keyword research, and SERP analysis.",tags:["Marketing & SEO","Writing & Content Creation"]},
{name:"Frase",rating:4.3,reviews:2800,views:"210K",desc:"AI content optimization platform for researching, writing, and optimizing SEO content.",tags:["Marketing & SEO","Writing & Content Creation"]},
{name:"Scalenut",rating:4.2,reviews:2200,views:"160K",desc:"AI-powered SEO and content marketing platform for planning and creating optimized content.",tags:["Marketing & SEO","Writing & Content Creation"]},
{name:"GrowthBar",rating:4.1,reviews:1600,views:"110K",desc:"AI writing tool focused on SEO blog posts with keyword research and competitor analysis.",tags:["Marketing & SEO","Writing & Content Creation"]},
{name:"MarketMuse",rating:4.2,reviews:1800,views:"130K",desc:"AI content planning and optimization platform for building topical authority.",tags:["Marketing & SEO"]},
{name:"INK AI",rating:4.0,reviews:1400,views:"95K",desc:"AI writing and SEO assistant that helps create content optimized for search engines.",tags:["Marketing & SEO","Writing & Content Creation"]},
{name:"Outranking",rating:4.1,reviews:1200,views:"80K",desc:"AI SEO writing tool for creating fact-based, optimized content with automated research.",tags:["Marketing & SEO","Writing & Content Creation"]},
{name:"Clearscope",rating:4.3,reviews:2000,views:"150K",desc:"AI content optimization platform used by enterprise teams for SEO-driven content.",tags:["Marketing & SEO"]},
{name:"AdCreative AI",rating:4.2,reviews:3400,views:"260K",desc:"AI tool that generates high-converting ad creatives for social media and display campaigns.",tags:["Marketing & SEO","Image Generation & Design"]},
{name:"Ocoya",rating:4.1,reviews:1600,views:"110K",desc:"AI social media management tool for creating, scheduling, and analyzing content.",tags:["Marketing & SEO","Productivity & Automation"]},

// Education & Study Tools
{name:"Khanmigo",rating:4.4,reviews:2800,views:"210K",desc:"Khan Academy's AI tutor providing personalized learning guidance and Socratic teaching.",tags:["Education & Study Tools","Chatbots & Conversational AI"]},
{name:"Socratic",rating:4.3,reviews:6200,views:"480K",desc:"Google's AI learning app that helps students with homework using visual explanations.",tags:["Education & Study Tools"]},
{name:"Quizlet AI",rating:4.4,reviews:8400,views:"720K",desc:"AI-enhanced flashcard platform with adaptive learning and AI-generated study materials.",tags:["Education & Study Tools"]},
{name:"Gradescope",rating:4.2,reviews:1800,views:"120K",desc:"AI-assisted grading platform for instructors to grade assignments faster and consistently.",tags:["Education & Study Tools"]},
{name:"Duolingo Max",rating:4.5,reviews:9200,views:"1.1M",desc:"AI-powered language learning with GPT-4 for roleplay conversations and mistake explanations.",tags:["Education & Study Tools"]},
{name:"Elicit",rating:4.3,reviews:2200,views:"160K",desc:"AI research assistant that finds and summarizes academic papers for literature reviews.",tags:["Education & Study Tools"]},
{name:"Scholarcy",rating:4.1,reviews:1400,views:"95K",desc:"AI tool that reads and summarizes research papers into flashcard-style summaries.",tags:["Education & Study Tools"]},
{name:"Explainpaper",rating:4.2,reviews:1600,views:"110K",desc:"AI tool that explains complex academic papers in simple language when you highlight text.",tags:["Education & Study Tools"]},
{name:"Perlego AI",rating:4.0,reviews:1200,views:"80K",desc:"AI-enhanced digital textbook library with smart search and study tools.",tags:["Education & Study Tools"]},
{name:"Wolfram Alpha AI",rating:4.5,reviews:7800,views:"620K",desc:"Computational intelligence engine for math, science, and data analysis with step-by-step solutions.",tags:["Education & Study Tools","Coding & Developer Tools"]},

// Audio, Voice & Music AI
{name:"ElevenLabs",rating:4.6,reviews:5800,views:"450K",desc:"Leading AI voice synthesis platform for realistic text-to-speech and voice cloning.",tags:["Audio, Voice & Music AI"]},
{name:"Murf AI",rating:4.3,reviews:3200,views:"240K",desc:"AI voice generator for creating studio-quality voiceovers for videos and presentations.",tags:["Audio, Voice & Music AI"]},
{name:"PlayHT",rating:4.2,reviews:2400,views:"180K",desc:"AI text-to-speech platform with ultra-realistic voices for podcasts and content.",tags:["Audio, Voice & Music AI"]},
{name:"Resemble AI",rating:4.1,reviews:1600,views:"110K",desc:"AI voice generator with real-time voice cloning and speech-to-speech capabilities.",tags:["Audio, Voice & Music AI"]},
{name:"Speechify",rating:4.4,reviews:6800,views:"520K",desc:"AI text-to-speech app that reads any text aloud with natural-sounding voices.",tags:["Audio, Voice & Music AI","Productivity & Automation"]},
{name:"Soundraw",rating:4.2,reviews:2000,views:"150K",desc:"AI music generator that creates royalty-free tracks customized to your needs.",tags:["Audio, Voice & Music AI"]},
{name:"AIVA",rating:4.3,reviews:2600,views:"190K",desc:"AI music composer that creates emotional soundtracks for films, games, and content.",tags:["Audio, Voice & Music AI"]},
{name:"Boomy",rating:4.0,reviews:1800,views:"130K",desc:"AI music creation platform where anyone can make and release original songs in seconds.",tags:["Audio, Voice & Music AI"]},
{name:"Voicemod AI",rating:4.1,reviews:3400,views:"260K",desc:"Real-time AI voice changer for gaming, streaming, and content creation.",tags:["Audio, Voice & Music AI"]},

// Misc / Emerging Tools
{name:"AutoGPT",rating:4.1,reviews:4200,views:"380K",desc:"Autonomous AI agent that chains GPT-4 calls to complete complex tasks independently.",tags:["Coding & Developer Tools","Productivity & Automation"]},
{name:"AgentGPT",rating:4.0,reviews:2800,views:"220K",desc:"Browser-based autonomous AI agent that plans and executes tasks toward a given goal.",tags:["Coding & Developer Tools","Productivity & Automation"]},
{name:"BabyAGI",rating:3.9,reviews:1800,views:"140K",desc:"Lightweight AI task management system that creates, prioritizes, and executes tasks autonomously.",tags:["Coding & Developer Tools","Productivity & Automation"]},
{name:"Hugging Face",rating:4.6,reviews:8400,views:"1.2M",desc:"The GitHub of machine learning — hosting models, datasets, and ML apps for the AI community.",tags:["Coding & Developer Tools"]},
{name:"Replicate",rating:4.3,reviews:3200,views:"250K",desc:"Cloud platform to run open-source AI models via API with simple deployment.",tags:["Coding & Developer Tools"]},
{name:"LangChain",rating:4.4,reviews:4600,views:"360K",desc:"Framework for building applications powered by language models with chains and agents.",tags:["Coding & Developer Tools"]},
{name:"Flowise",rating:4.2,reviews:2000,views:"150K",desc:"Open-source drag-and-drop tool for building LLM apps and chatbots visually.",tags:["Coding & Developer Tools"]},
{name:"Jan AI",rating:4.1,reviews:1600,views:"110K",desc:"Open-source desktop app for running AI models locally with full privacy.",tags:["Coding & Developer Tools","Chatbots & Conversational AI"]},
{name:"LM Studio",rating:4.3,reviews:3400,views:"260K",desc:"Desktop app to discover, download, and run local LLMs with a clean interface.",tags:["Coding & Developer Tools","Chatbots & Conversational AI"]},
{name:"AnythingLLM",rating:4.1,reviews:1400,views:"95K",desc:"All-in-one AI app for chatting with documents using any LLM, locally or in the cloud.",tags:["Coding & Developer Tools","Chatbots & Conversational AI"]},
{name:"Descript Audio",rating:4.3,reviews:2200,views:"170K",desc:"AI-powered audio editing with transcription-based editing, filler word removal, and studio sound.",tags:["Audio, Voice & Music AI","Video Creation & Editing"]}
];
